{% set version = "1.11.0" %}

package:
  name: sigmf
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sigmf/sigmf-{{ version }}.tar.gz
  sha256: dda43bee94e52f5df97edfa139e48a3d884db1c4e80c96555cebcaeff6e05e2f

build:
  entry_points:
    - sigmf_validate = sigmf.validate:main
    - sigmf_convert = sigmf.convert.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=65.0
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - jsonschema
    - defusedxml
    - packaging

test:
  imports:
    - sigmf
  commands:
    - pip check
    - sigmf_validate --help
    - sigmf_convert --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sigmf/sigmf-python
  summary: Easily interact with Signal Metadata Format (SigMF) recordings.
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING-LGPL

extra:
  recipe-maintainers:
    - Teque5
